const cfg=window.MOBEATS_CONFIG||{};const statusEl=document.querySelector("#status");let sb=null,session=null;
const $=s=>document.querySelector(s);const slugify=s=>s.toLowerCase().trim().replace(/[^a-z0-9äöüß]+/gi,"-").replace(/^-|-$/g,"");
function msg(s){statusEl.textContent=s}
async function init(){if(!cfg.supabaseUrl||!cfg.supabasePublishableKey){msg("Supabase ist noch nicht verbunden. Trage URL und Publishable Key in supabase-config.js ein.");return}sb=window.supabase.createClient(cfg.supabaseUrl,cfg.supabasePublishableKey);const r=await sb.auth.getSession();session=r.data.session;await refresh();sb.auth.onAuthStateChange((_e,s)=>{session=s;refresh()})}
async function refresh(){if(!sb)return;if(!session){$("#loginPanel").hidden=false;$("#dashboard").hidden=true;$("#logout").hidden=true;return}const {data:user}=await sb.auth.getUser();const {data:admin}=await sb.from("admin_users").select("user_id").eq("user_id",user.user.id).maybeSingle();if(!admin){msg("Dieser Benutzer ist kein CMS-Administrator.");await sb.auth.signOut();return}$("#loginPanel").hidden=true;$("#dashboard").hidden=false;$("#logout").hidden=false;await loadArtists();await loadTracks()}
$("#login").onclick=async()=>{if(!sb)return msg("Supabase-Konfiguration fehlt.");const {error}=await sb.auth.signInWithPassword({email:$("#email").value,password:$("#password").value});if(error)msg(error.message)};
$("#logout").onclick=()=>sb?.auth.signOut();
async function loadArtists(){const {data,error}=await sb.from("artists").select("id,name").order("name");if(error)return msg(error.message);$("#trackArtist").innerHTML=(data||[]).map(a=>`<option value="${a.id}">${a.name}</option>`).join("")}
async function loadTracks(){const {data,error}=await sb.from("tracks").select("id,title,slug,genre,bpm,is_published,artists(name)").order("created_at",{ascending:false});if(error)return msg(error.message);$("#adminTracks").innerHTML=(data||[]).map(t=>`<div class="admin-row"><span><b>${t.title}</b><small>${t.artists?.name||"—"} · ${t.genre} · ${t.bpm} BPM</small></span><span>${t.is_published?"PUBLIC":"DRAFT"}</span></div>`).join("")||"<p class='hint'>Noch keine Tracks.</p>"}
async function upload(bucket,file){if(!file)return"";const path=Date.now()+"-"+slugify(file.name);const r=await sb.storage.from(bucket).upload(path,file,{upsert:false});if(r.error)throw r.error;return sb.storage.from(bucket).getPublicUrl(path).data.publicUrl}
$("#saveArtist").onclick=async()=>{try{const name=$("#artistName").value.trim();const {error}=await sb.from("artists").insert({name,slug:$("#artistSlug").value.trim()||slugify(name),genre:$("#artistGenre").value.trim(),bio:$("#artistBio").value.trim()});if(error)throw error;msg("Artist gespeichert.");await loadArtists()}catch(e){msg(e.message)}};
$("#saveTrack").onclick=async()=>{try{const title=$("#trackTitle").value.trim();const audio=await upload("music",$("#audioFile").files[0]);if(!audio)throw Error("Bitte eine MP3 auswählen.");const cover=await upload("covers",$("#coverFile").files[0]);const {error}=await sb.from("tracks").insert({title,slug:$("#trackSlug").value.trim()||slugify(title),artist_id:$("#trackArtist").value,genre:$("#trackGenre").value.trim(),bpm:Number($("#trackBpm").value)||0,audio_url:audio,cover_url:cover,is_published:$("#published").checked});if(error)throw error;msg("Track gespeichert.");await loadTracks()}catch(e){msg(e.message)}};
$("#savePlaylist").onclick=async()=>{try{const name=$("#playlistName").value.trim();const {error}=await sb.from("playlists").insert({name,slug:$("#playlistSlug").value.trim()||slugify(name),description:$("#playlistDesc").value.trim(),is_published:$("#playlistPublished").checked});if(error)throw error;msg("Playlist gespeichert.")}catch(e){msg(e.message)}};
init();