create extension if not exists pgcrypto;
create table if not exists public.artists(id uuid primary key default gen_random_uuid(),name text not null,slug text unique not null,bio text default '',genre text default '',avatar_url text default '',created_at timestamptz default now());
create table if not exists public.tracks(id uuid primary key default gen_random_uuid(),title text not null,slug text unique not null,artist_id uuid references public.artists(id) on delete set null,genre text default '',bpm integer default 0,audio_url text not null,cover_url text default '',duration_seconds integer default 0,is_published boolean default false,created_at timestamptz default now());
create table if not exists public.playlists(id uuid primary key default gen_random_uuid(),name text not null,slug text unique not null,description text default '',cover_url text default '',is_published boolean default false,created_at timestamptz default now());
create table if not exists public.playlist_tracks(playlist_id uuid references public.playlists(id) on delete cascade,track_id uuid references public.tracks(id) on delete cascade,position integer default 0,primary key(playlist_id,track_id));
create table if not exists public.admin_users(user_id uuid primary key references auth.users(id) on delete cascade,is_active boolean default true);\nalter table public.admin_users enable row level security;\ncreate policy if not exists "admins self" on public.admin_users for select to authenticated using (user_id=auth.uid());\n\nalter table public.artists enable row level security;
alter table public.tracks enable row level security;
alter table public.playlists enable row level security;
alter table public.playlist_tracks enable row level security;
drop policy if exists "public artists" on public.artists;
drop policy if exists "public tracks" on public.tracks;
drop policy if exists "public playlists" on public.playlists;
drop policy if exists "public playlist tracks" on public.playlist_tracks;
create policy "public artists" on public.artists for select using (true);
create policy "public tracks" on public.tracks for select using (is_published=true);
create policy "public playlists" on public.playlists for select using (is_published=true);
create policy "public playlist tracks" on public.playlist_tracks for select using (exists(select 1 from public.playlists p where p.id=playlist_id and p.is_published=true));
create or replace function public.is_admin() returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.admin_users where user_id=auth.uid() and is_active=true); $$;
create table if not exists public.admin_users(user_id uuid primary key references auth.users(id) on delete cascade,is_active boolean default true);
alter table public.admin_users enable row level security;
create policy "admins self" on public.admin_users for select to authenticated using (user_id=auth.uid());
create policy "admin artists" on public.artists for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "admin tracks" on public.tracks for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "admin playlists" on public.playlists for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "admin playlist tracks" on public.playlist_tracks for all to authenticated using (public.is_admin()) with check (public.is_admin());
insert into storage.buckets(id,name,public) values ('music', 'music', true) on conflict(id) do nothing;
insert into storage.buckets(id,name,public) values ('covers', 'covers', true) on conflict(id) do nothing;
drop policy if exists "public music read" on storage.objects;
drop policy if exists "admin music write" on storage.objects;
drop policy if exists "public covers read" on storage.objects;
drop policy if exists "admin covers write" on storage.objects;
create policy "public music read" on storage.objects for select using (bucket_id='music');
create policy "public covers read" on storage.objects for select using (bucket_id='covers');
create policy "admin music write" on storage.objects for all to authenticated using (bucket_id='music' and public.is_admin()) with check (bucket_id='music' and public.is_admin());
create policy "admin covers write" on storage.objects for all to authenticated using (bucket_id='covers' and public.is_admin()) with check (bucket_id='covers' and public.is_admin());